### ISSUE TITLE
Nothing happened!

### ISSUE THREAD

**Issue by beeflin** [BitesPotatoBacks/LegacySystemPreferences#2]
I've followed the instructions but my Legacy System Preferences app doesn't load any panes. Halp!

**Comment by dehydratedpotato** [comment]
@beeflin 
Okay, let's double check the steps then...
1. Are the panes extended with `.prefpane`?
2. What directory did you put the panes in? Did you make `/Library/LegacyPrefPanes` or reuse `/Library/PreferencePanes`?
3. Did you make sure to use the `pane_stripper.sh` tool in the dir the panes reside in?

**Comment by beeflin** [comment]
1,2,3 Yes, I did all that. /Library/PreferencePanes is in the Library on the root of my HD, not my user Library.
Does my HD need to be named "Macintosh HD"? It's named "Lamp Post". That's the only thing I can think of.

**Comment by dehydratedpotato** [comment]
@beeflin 
> /Library/PreferencePanes is in the Library on the root of my HD, not my user Library.

By that you mean your panes are in the _system_ library? I.e. `/System/Library/PreferencePanes`? You'll need to put them in your user Library if that's the case, so just `/Library/PreferencePanes`.

The project works this way on purpose, so the leftover broken panes that still reside in the system library (well, they exist on my install of Ventura) don't cause any conflicts.

> Does my HD need to be named "Macintosh HD"? It's named "Lamp Post". That's the only thing I can think of.

That shouldn't be the case because the project accesses Library paths relatively...

**Comment by beeflin** [comment]
No,  I didn't mean they're in HD/System/Library/LegacyPrefPanes. They're in HD/Library/LegacyPrefPanes.

I just meant they're not in HD/Users/Library/LegacyPrefPanes. (I just tried that, by the way. Still no joy.)

**Comment by beeflin** [comment]
Here's a screenshot, showing the path at the bottom of the window:

<img width="763" alt="Screenshot 2023-04-25 at 13 40 38" src="https://user-images.githubusercontent.com/17083024/234279417-306cc728-49eb-4953-b1b8-7929c17d49e4.png">

**Comment by thetrueyoshifan** [comment]
.prefPane is case sensitive. Rename them all to be ``*.prefPane`` instead. You can do so automatically using this Terminal command (make sure you're navigated to /Library/LegacyPrefPanels first)

```bash
for file in *.prefpane; do; sudo mv $file "${file%%.prefpane}.prefPane"; done
```

**Comment by beeflin** [comment]
Thank you so much!

**Comment by dehydratedpotato** [comment]
@thetrueyoshifan 👏👏
